version: "3"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - fuseki
    environment:
      - FUSEKI_URL=http://fuseki:3030
      - FUSEKI_DATASET=ds

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "4030:3030"
    environment:
      - ADMIN_PASSWORD=admin123
      - JVM_ARGS=-Xmx2g
    volumes:
      - ./fuseki-data:/fuseki
      - ./config.ttl:/fuseki/config.ttl
    command: "--config=/fuseki/config.ttl"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "4080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - fuseki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
