version: '3'
services:
  app:
    build: .
    ports:
      # world-facing
      - "3770:3770"
      # internal
      - "8311:8311"
    volumes:
      # Bind mount for application code
      - ./app:/home/myuser/app
      # Named volume for persistent data
      - data_volume:/home/myuser/data
      # Bind mount for logs (example)
      - ./logs:/var/log/myapp
    environment:
      - NODE_ENV=production

volumes:
  data_volume:
