version: "3"
services:
  ssh-server:
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./shared_data:/shared_data

  app:
    build:
      context: ./services/app
    ports:
      - "4000:8311"
    depends_on:
      - fuseki
    environment:
      - FUSEKI_URL=http://fuseki:3030
      - FUSEKI_DATASET=semem

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "4030:3030"
    volumes:
      - ./data/fuseki:/fuseki/databases
    environment:
      - ADMIN_PASSWORD=admin123
      - FUSEKI_DATASET_1=ds
      - FUSEKI_DATASET_2=semem
      - FUSEKI_DATASET_3=test-db
      - FUSEKI_DATASET_4=test-mem
      - JVM_ARGS=-Xmx2g

  nginx:
    image: nginx:alpine
    ports:
      - "4080:4080"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/web/public:/usr/share/nginx/html:ro
    depends_on:
      - app
      - fuseki

  xmpp:
    image: prosody/prosody
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5282:5282"
    volumes:
      - ./data/uploads:/var/lib/prosody/http_upload
      - ./config/prosody/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
      - ./config/certs:/etc/prosody/certs:ro
      - ./data/prosody:/var/lib/prosody
    environment:
      - PROSODY_GENERATE_CERTS=true
      - PROSODY_MAX_UPLOAD_SIZE=104857600
      - PROSODY_ADMIN_JID=admin@localhost
      - PROSODY_ADMIN_PASSWORD=admin123
      - PROSODY_MONITORING=true
      - PROSODY_MONITORING_PORT=5282
    healthcheck:
      test: ["CMD-SHELL", "prosodyctl status"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  monitor:
    build:
      context: ./services/monitor
    ports:
      - "4040:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - app
      - fuseki
      - xmpp
