FROM prosody/prosody

USER root
RUN mkdir -p /var/lib/prosody/logs && \
    touch /var/lib/prosody/logs/prosody.log /var/lib/prosody/logs/error.log && \
    chown -R prosody:prosody /var/lib/prosody

# Copy entrypoint and user creation scripts
COPY config/prosody/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY config/prosody/prosody-init-users.sh /usr/local/bin/prosody-init-users.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh /usr/local/bin/prosody-init-users.sh

USER prosody

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]