version: "3"
services:
  app:
    build: .
    ports:
      - "4000:8311"
    depends_on:
      - fuseki
    environment:
      - FUSEKI_URL=http://fuseki:3030
      - FUSEKI_DATASET=ds

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "4030:3030"
    environment:
      - ADMIN_PASSWORD=admin123
      - FUSEKI_DATASET_1=ds
      - FUSEKI_DATASET_ds=/fuseki/databases/ds
    volumes:
      - ./fuseki-data:/fuseki
      - ./config.ttl:/fuseki/config.ttl

  nginx:
    image: nginx:alpine
    ports:
      - "4080:4080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - fuseki