global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    
  - job_name: 'tbox-services'
    static_configs:
      - targets: ['app:8311', 'monitor:8080']
        labels:
          service: 'tbox'
          
  - job_name: 'fuseki'
    metrics_path: '/$/metrics'
    static_configs:
      - targets: ['fuseki:3030']
    basic_auth:
      username: 'admin'
      password: 'admin123'