-- Get the domain from PROSODY_DOMAIN environment variable, default to "localhost"
-- This default matches the behavior of ensure-prosody-certs.sh if PROSODY_DOMAIN is unset.
local domain = os.getenv("PROSODY_DOMAIN") or "localhost"

admins = { "admin@" .. domain }

modules_enabled = {
    "roster"; "saslauth"; "tls"; "dialback"; "disco";
    "ping"; "register"; -- Removed "posix" to prevent daemonization
    "admin_adhoc"; "offline"; "c2s"; "s2s";
    "vcard"; "pep"; -- PEP (Personal Eventing Protocol) is good for vcard-temp, avatars, etc. and uses pubsub
    "mam"; -- Message Archive Management
    "carbons"; -- Message Carbons for message synchronization across multiple clients
    -- Add other global modules here as needed
}

modules_disabled = {
    "posix"; -- Explicitly disable posix module to prevent daemonization
}

-- Authentication settings
authentication = "internal_plain"
-- It's generally recommended to set allow_unencrypted_plain_auth to false
-- when c2s_require_encryption is true. Plain SASL mechanisms will then only
-- be offered over an already encrypted TLS connection.
allow_unencrypted_plain_auth = false
c2s_require_encryption = true -- Enforce encryption for client-to-server
s2s_require_encryption = true -- Enforce encryption for server-to-server

-- Registration settings
allow_registration = true
-- Conflict management - if a second connection with the same resource connects, kick the first one
conflict_resolve = "kick_oldest"

-- Logging configuration
log = {
    debug = "*console"; -- For development. For production, consider "info" or "warn" and file logging.
    -- info = "/var/log/prosody/prosody.log";
    -- error = "/var/log/prosody/prosody.err";
}

-- Global SSL settings, primarily for DH params.
-- Certificates are best defined per VirtualHost.
ssl = {
    dhparam = "/etc/prosody/certs/dh.pem"; -- Generated by ensure-prosody-certs.sh
}

-- HTTP server configuration removed for stability

-- Define the main virtual host based on the PROSODY_DOMAIN
VirtualHost(domain)
    ssl = {
        key = "/etc/prosody/certs/" .. domain .. ".key";
        certificate = "/etc/prosody/certs/" .. domain .. ".crt";
    }
    -- authentication and allow_unencrypted_plain_auth are inherited from global settings.
    -- No need to repeat them here unless you want to override for this specific VirtualHost.

-- Additional virtual hosts can be added here

-- Component configurations (like MUC) should be in conf.d/
-- Remove static component definitions from here.

-- Include configuration files from conf.d directory (e.g., for MUC components)
include "conf.d/*.cfg.lua"